config/routes.rb
Rails.application.routes.draw do


  resources :users, except: :index do
      resources :photos
      resources :families, except: :index do
        resources :photos
        resources :people, shallow: true do
          resources :ethnicities, only: [:new, :create, :edit, :update, :destroy]
          resources :relationships, only: [:new, :create, :edit, :update, :destroy]
          resources :partnerships, only: [:new, :create, :edit, :update, :destroy]

        end
      end
  end
  get '/users/:user_id/people/new', to: 'people#new'
  post '/users/:user_id/people', to: 'people#create', as: 'user_people'
  get '/sign_in', to: 'sessions#new'
  post '/sign_in', to: 'sessions#create'
  delete '/sign_out', to: 'sessions#destroy'
  get '/', to: 'sessions#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/person.rb
class Person < ApplicationRecord
  has_many :parent_relationships, class_name: "Relationship", foreign_key: "child_id"
  has_many :child_relationships, class_name: "Relationship", foreign_key: "parent_id"
  has_many :parents, through: :parent_relationships
  has_many :children, through: :child_relationships
  has_many :partnerships
  has_many :partners, through: :partnerships, foreign_key: "partner_id"
  has_many :ethnicities
  belongs_to :family, optional: true
  has_many :photos
  belongs_to :user, optional: true

  validates :first_name, :last_name, :dob, :place_of_birth, :current_location, presence: true
  accepts_nested_attributes_for :photos



  def to_s
    self.first_name + " " + self.last_name
  end

  def my_ethnicities
    new_hash = {}
    total = 0
    if self.blood_related_parents.empty?
      new_hash["Unknown"] = 100
    else
      self.blood_related_parents.each do |parent|
        if parent.ethnicities.empty?
          new_hash["Unknown"] = 50
          total += 50
        else
          parent.ethnicities.each do |ethnicity|
            half_percentage = ethnicity.percentage/2
            total += half_percentage
            if new_hash.has_key?(ethnicity.name)
              new_hash[ethnicity.name] += half_percentage
            else
              new_hash[ethnicity.name] = half_percentage
            end
          end
        end
      end
      if total < 100 && new_hash.has_key?("Unknown")
        new_hash["Unknown"] += (100 - total)
      elsif total < 100
        new_hash["Unknown"] = (100 - total)
      end
    end
    new_hash
  end

  def blood_related_parents
    a = self.parents.select do |parent|
      Relationship.find_by(parent: parent, child: self).blood_related
    end
    a
  end

  def non_blood_related_parents
    a = self.parents.select do |parent|
      !Relationship.find_by(parent: parent, child: self).blood_related
    end
    a
  end

  def p_relationship(parent)
    b = self.parent_relationships.select do |rel|
      rel.parent == parent
    end
  end

  def all_parents
    p_hash = {}
    self.parent_relationships.each do |rel|
      if rel.blood_related && rel.parent.gender.downcase == "male"
        p_hash[rel.parent.to_s] = "father"
      elsif rel.blood_related && rel.parent.gender.downcase == "female"
        p_hash[rel.parent.to_s] = "mother"
      elsif rel.parent.gender.downcase == "male"
        p_hash[rel.parent.to_s] = "stepfather"
      elsif rel.parent.gender.downcase == "female"
        p_hash[rel.parent.to_s] = "stepmother"
      end
    end
    p_hash
  end

  def all_children
    c_hash = {}
    self.child_relationships.each do |rel|
      if rel.blood_related && rel.child.gender.downcase == "male"
        c_hash[rel.child.to_s] = "son"
      elsif rel.blood_related && rel.child.gender.downcase == "female"
        c_hash[rel.child.to_s] = "daughter"
      elsif rel.child.gender.downcase == "male"
        c_hash[rel.child.to_s] = "adopted son"
      elsif child.gender.downcase == "female"
        c_hash[rel.child.to_s] = "adopted daughter"
      end
    end
    c_hash
  end


  def all_siblings
    sibs_hash = {}
    self.parents.each do |parent|
      parent.children.each do |child|
        if child != self
          if self.blood_related_parents.include?(parent) && child.gender.downcase == "male"
            sibs_hash[child.to_s] = "brother"
          elsif self.blood_related_parents.include?(parent) && child.gender.downcase == "female"
            sibs_hash[child.to_s] = "sister"
          elsif child.gender.downcase == "male"
            sibs_hash[child.to_s] = "stepbrother"
          elsif child.gender.downcase == "female"
            sibs_hash[child.to_s] = "stepsister"
          end
        end
      end
    end
    sibs_hash
  end

  def all_grandparents
    parents_hash = {}
    self.parents.each do |parent|
      parent.parents.each do |gp|
        if self.blood_related_parents.include?(parent) && parent.blood_related_parents.include?(gp) && gp.gender.downcase == "male"
          parents_hash[gp.to_s] = "grandfather"
        elsif self.blood_related_parents.include?(parent) && parent.blood_related_parents.include?(gp) && gp.gender.downcase == "female"
          parents_hash[gp.to_s] = "grandmother"
        elsif gp.gender.downcase == "male"
          parents_hash[gp.to_s] = "grandfather - not blood-related"
        elsif gp.gender.downcase == "female"
          parents_hash[gp.to_s] = "grandfather - not blood-related"
        end
      end
    end
    parents_hash
  end

  def all_neices_nephews
    nn_hash = {}
    self.parents.each do |parent|
      parent.children.each do |sib|
        if sib != self
          sib.children.each do |nn|
            if self.blood_related_parents.include?(parent) && sib.blood_related_parents.include?(parent) && nn.blood_related_parents.include?(sib) && gp.gender.downcase == "male"
              nn_hash[nn.to_s] = "nephew"
            elsif self.blood_related_parents.include?(parent) && sib.blood_related_parents.include?(parent) && nn.blood_related_parents.include?(sib) && gp.gender.downcase == "female"
              nn_hash[nn.to_s] = "neice"
            elsif nn.gender.downcase == "male"
              nn_hash[nn.to_s] = "nephew - not blood-related"
            elsif nn.gender.downcase == "female"
              nn_hash[nn.to_s] = "neice - not blood-related"
            end
          end
        end
      end
    end
    nn_hash
  end

  def all_aunts_uncles
    au_hash = {}
    self.parents.each do |parent|
      parent.siblings.each do |sib|
        if self.blood_related_parents.include?(parent) && sib.gender.downcase == "male"
          au_hash[sib.to_s] = "uncle"
        elsif self.blood_related_parents.include?(parent) && sib.gender.downcase == "female"
          au_hash[sib.to_s] = "aunt"
        elsif sib.gender.downcase == "male"
          au_hash[sib.to_s] = "uncle - not blood-related"
        elsif sib.gender.downcase == "female"
          au_hash[sib.to_s] = "aunt - not blood-related"
        end
      end
    end
    au_hash
  end

  def all_cousins
    cuz_hash = {}
    self.parents.each do |parent|
      parent.siblings.each do |au|
        au.children.each do |cuz|
          if !parent.all_siblings[au.to_s].include?("step") && self.blood_related_parents.include?(parent) && cuz.blood_related_parents.include?(au)
            cuz_hash[cuz.to_s] = "cousin"
          else
            cuz_hash[cuz.to_s] = "cousin - not blood-related"
          end
        end
      end
    end
    cuz_hash
  end

  def all_family_members
    fam_hash = {}
    fam_array = [self.all_cousins, self.all_parents, self.all_siblings, self.all_children, self.all_aunts_uncles, self.all_grandparents, self.all_neices_nephews]
    fam_array.each do |hash|
      hash.each do |key, value|
        fam_hash[key] = value
      end
    end
    fam_hash
  end

  def siblings
    sibs_array = []
    self.parents.each do |parent|
      parent.children.each do |child|
        if !sibs_array.include?(child)
          sibs_array << child
        end
      end
    end
    sibs_array.delete(self)
    sibs_array
  end

  def grandparents
    g_array = []
    self.parents.each do |parent|
      # if parent.blood_related == true
      parent.parents.each do |gparent|
        g_array << gparent
      end
    end
    g_array
  end

  def full_name
    "#{self.first_name} #{self.last_name}"
  end

  def self_portrait
     self.photos.find {|photo| photo.photo_type == "profile picture"}
  end

  def family_portrait
    self.family.find {|photo| photo.photo_type == "family portrait"}
  end

  def age
    Date.today.year - self.dob.year
  end



end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :person, only: [:show, :edit, :update, :destroy]
  before_action :family, only: [:index]

  def index
    @people = @family.people
  end

  def show
    @family = @person.family
  end

  def new
    if params[:family_id]
      @family = Family.find(params[:family_id])
      @person = @family.people.build
    else
      @person = Person.new
    end
  end

  def create
    if params[:family_id]
      @family = Family.find(params[:family_id])
      @person = @family.people.build(person_params)
    else

      @person = Person.new(person_params)
    end
    if @person.save
      redirect_to person_path(@person)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @person.update(person_params)
      redirect_to person_path(@person)
    else
      render :edit
    end
  end

  def destroy
    @family = @person.family
    @person.destroy
    redirect_to user_path(@user)
  end

private

  def person_params
    params.require(:person).permit(:first_name, :last_name, :dob, :dod, :deceased, :gender, :place_of_birth, :current_location, :user_id)
  end

  def person
    @person = Person.find(params[:id])
  end

  def family
    @family = Family.find(params[:family_id])
  end

  def check_authentication
    if !user_is_signed_in
      flash[:alert] = "you need to sign in to view that"
      redirect_to sign_in_path
    end
  end

  def user_is_signed_in
    @user = User.find(session[:user_id])
    if params[:id]
      @person = Person.find(params[:id])
    end
    if params[:user_id]
      session[:user_id] == params[:user_id].to_i
    elsif params[:person_id] || params[:id]
      @user.family == @person.family
    else
      @user = User.find(session[:user_id])
    end
  end


end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_form.html.erb
  <%= f.label :first_name %><br>
  <%= f.text_field :first_name %><br>
  <%= f.label :last_name %><br>
  <%= f.text_field :last_name %><br>
  <%= f.label :dob, "Date of birth - format: 'YYYY-MM-DD'" %><br>
  <%= f.text_field :dob %><br>
  <%= f.label :deceased, "Deceased?" %><br>
  <%= f.check_box :deceased %><br>
  <%= f.label :dod, "Date deceased (optional)  - format: 'YYYY-MM-DD'" %><br>
  <%= f.text_field :dod %><br>
  <%= f.label :place_of_birth %><br>
  <%= f.text_field :place_of_birth %><br>
  <%= f.label :current_location %><br>
  <%= f.text_field :current_location %><br>

app/views/people/edit.html.erb
<h1>Edit Form</h1>

<%= form_for @person do |f| %>
  <%= f.label :first_name %><br>
  <%= f.text_field :first_name %><br>
  <%= f.label :last_name %><br>
  <%= f.text_field :last_name %><br>
  <%= f.label :dob, "Date of birth - format: 'YYYY-MM-DD'" %><br>
  <%= f.text_field :dob %><br>
  <%= f.label :deceased, "Deceased?" %><br>
  <%= f.check_box :deceased %><br>
  <%= f.label :dod, "Date deceased (optional)  - format: 'YYYY-MM-DD'" %><br>
  <%= f.text_field :dod %><br>
  <%= f.label :place_of_birth %><br>
  <%= f.text_field :place_of_birth %><br>
  <%= f.label :current_location %><br>
  <%= f.text_field :current_location %><br>
  <%= f.label :gender %><br>
  <%= f.text_field :gender %><br>
  <%= f.submit %>
<% end %>

<% @person.errors.messages.each do |attribute, message| %>
  <% if !message.empty? %>
    <p style="color:red"><%= message %></p>
  <% end %>
<% end %>

app/views/people/index.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title><%= @family.name %></title>
  </head>
  <body>

<h1><%= @family.name %> Members</h1>


<%= form_tag new_user_family_person_path(@user, @family), method: "get" do %>
<%= submit_tag "Add Family Member" %>
<% end %><br>

<%= link_to '<button type="button">Return to Family Page</button>'.html_safe, user_family_path(@user, @family) %>
<br>

<ul>
<% @people.each do |person|%>
  <li><%= link_to person, person_path(person) %><%= @user.person.all_family_members[person.to_s] ? " - Your #{@user.person.all_family_members[person.to_s]}" : "" %></li>
<% end %>
</ul>

</body>
</html>

app/views/people/new.html.erb
<h1>Create New Person</h1>

<% if params[:family_id] %>
<%= form_for @person, url: user_family_people_path(@user, @user.family) do |f| %>
  <%= f.label :first_name %><br>
  <%= f.text_field :first_name %><br>
  <%= f.label :last_name %><br>
  <%= f.text_field :last_name %><br>
  <%= f.label :dob, "Date of birth - format: 'YYYY-MM-DD'" %><br>
  <%= f.text_field :dob %><br>
  <%= f.label :deceased, "Deceased?" %><br>
  <%= f.check_box :deceased %><br>
  <%= f.label :dod, "Date deceased (optional)  - format: 'YYYY-MM-DD'" %><br>
  <%= f.text_field :dod %><br>
  <%= f.label :place_of_birth %><br>
  <%= f.text_field :place_of_birth %><br>
  <%= f.label :current_location %><br>
  <%= f.text_field :current_location %><br>
  <%= f.label :gender %><br>
  <%= f.text_field :gender %><br>
  <%= f.submit %>
<% end %>
<% else %>
<%= form_for @person, url: user_people_path(@user) do |f| %>
  <%= f.label :user_id %><br>
  <%= f.collection_select :user_id, [@user], :id, :to_s %><br>
  <%= f.label :first_name %><br>
  <%= f.text_field :first_name %><br>
  <%= f.label :last_name %><br>
  <%= f.text_field :last_name %><br>
  <%= f.label :dob, "Date of birth - format: 'YYYY-MM-DD'" %><br>
  <%= f.text_field :dob %><br>
  <%= f.label :deceased, "Deceased?" %><br>
  <%= f.check_box :deceased %><br>
  <%= f.label :dod, "Date deceased (optional)  - format: 'YYYY-MM-DD'" %><br>
  <%= f.text_field :dod %><br>
  <%= f.label :place_of_birth %><br>
  <%= f.text_field :place_of_birth %><br>
  <%= f.label :current_location %><br>
  <%= f.text_field :current_location %><br>
  <%= f.label :gender %><br>
  <%= f.text_field :gender %><br>
  <%= f.submit %>
<% end %>
<% end %>

<% @person.errors.messages.each do |attribute, message| %>
  <% if !message.empty? %>
    <p style="color:red"><%= message %></p>
  <% end %>
<% end %>

app/views/people/show.html.erb
<h1><%= @person.to_s %></h1><br>


  <% if @person.self_portrait %>
    <%= image_tag @person.self_portrait.img_url, :size => "725x450"%><br>
    <br>
    <%= link_to '<button type="button">Edit Profile Picture</button>'.html_safe, edit_user_photo_path(@user, @person.self_portrait) %><br>
  <% elsif @user.family %>
    <%= link_to '<button type="button">Add Profile Picture</button>'.html_safe, new_user_photo_path(@user) %><br>
  <% end %>
<p>Birthday: <%= @person.dob.strftime("%B %d, %Y") %></p>
<p>Age: <%= @person.age %></p>
<% if @person.deceased %>
<p>Died: <%= @person.dod %></p>
<% end %>
<p>Place Of Birth: <%= @person.place_of_birth %></p>
<p>Current Location: <%= @person.current_location %></p>
<p>Gender: <%= @person.gender.capitalize %></p>

<%= form_tag edit_person_path(@person), method: "get" do %>
<%= submit_tag "Edit Personal Information" %>
<% end %>



<br>
<% if !@user.family %>
 <h2>Next, you should add yourself to a family!</h2>
 <%= form_tag new_user_family_path(@user), method: "get" do %>
 <%= submit_tag "Create Your Family" %>
 <% end %>
<% elsif @user.family %>
  <%= link_to '<button type="button">Go Back To Family Page</button>'.html_safe, user_family_path(@user, @user.family) %>

  <h2>Ethnicities:</h2>

  <p>Ethnicities Calculated From Relatives</p>
  <ul>
  <% @person.my_ethnicities.each do |key, value| %>
    <li><%= key + " - " + value.to_s + "% "%></li>
  <% end %>
  </ul>

  <p>Current Ethnicity Records<p>
  <ul>
  <% @person.ethnicities.each do |ethnicity| %>
    <li><%= ethnicity.name + " - " + ethnicity.percentage.to_s + "% "%>
    <%= link_to "Edit", edit_ethnicity_path(ethnicity)%> :: <%= link_to "Delete", ethnicity_path(ethnicity), method: "delete"%></li>
  <% end %>
  </ul>
  <% if @person.ethnicities.empty? %>
  <p> This person doesn't have any recorded ethnicities. Would you like to add one?</p>
  <% end %>

  <%= form_tag new_person_ethnicity_path(@person), method: "get" do %>
  <%= submit_tag "Add An Ethnicity" %>
  <% end %>


   <% if !@person.partners.empty? %>
     <h2><%= @person.first_name %>'s Partners: </h2>
       <ul>
       <% @person.partnerships.each do |partnership| %>
        <li>
         <%= link_to partnership.partner, person_path(partnership.partner) %> - <%= partnership.status.capitalize %><br>
           <%= link_to "Edit Record", edit_partnership_path(partnership)%> :: <%= link_to "Delete Partnership", partnership_path(partnership), method: "delete"%></li>
       <% end %>
       </ul>
   <% end %>


  <% if !@person.children.empty? %>
    <h2><%= @person.first_name %>'s Children: </h2>
      <ul>
      <% @person.children.each do |child| %>
        <li><%= link_to child.to_s, person_path(child) %><br>
        <% @relationship = @person.child_relationships.find {|rel| rel.child == child} %>
          <%= link_to "Edit Record", edit_relationship_path(@relationship)%> :: <%= link_to "Delete Relationship", relationship_path(@relationship), method: "delete"%></li>
      <% end %>
      </ul>
  <% end %>

  <% if !@person.parents.empty? %>
    <h2><%= @person.first_name %>'s Parents: </h2>
      <ul>
      <% @person.parents.each do |parent| %>
        <li><%= link_to parent.to_s, person_path(parent) %><br>
          <% @relationship = @person.parent_relationships.find {|rel| rel.parent == parent} %>
            <%= link_to "Edit Record", edit_relationship_path(@relationship)%> :: <%= link_to "Delete Relationship", relationship_path(@relationship), method: "delete"%></li>
      <% end %>
      </ul>
  <% end %>

  <% if !@person.siblings.empty? %>
    <h2><%= @person.first_name %>'s Siblings: </h2>
      <ul>
      <% @person.siblings.each do |sibling| %>
        <li><%= link_to sibling.to_s, person_path(sibling) %></li>
      <% end %>
      </ul>
  <% end %>

  <h3>Add relationships:</h3>
  <p>Note: You can only add a partnership with an existing person record.</p>
  <p>If you'd like to create a new person, please go back to the <%= link_to "family page", user_family_people_path(@user, @family)%>.</p>

  <%= form_tag new_person_relationship_path(@person), method: "get" do %>
  <%= submit_tag "Create New Parent Or Child Relationship" %>
  <% end %>
  <br>
  <%= form_tag new_person_partnership_path(@person), method: "get" do %>
  <%= submit_tag "Create New Partnership" %>
  <% end %>
  <br>
  <% if @person != @user.person %>
    <%= form_for @person, method: "delete" do |f| %>
    <%= f.submit "Delete Person"%>
    <% end %> <br>
  <% end %>
<% end %>