config/routes.rb
Rails.application.routes.draw do


  resources :users, except: :index do
      resources :photos
      resources :families, except: :index do
        resources :photos
        resources :people, shallow: true do
          resources :ethnicities, only: [:new, :create, :edit, :update, :destroy]
          resources :relationships, only: [:new, :create, :edit, :update, :destroy]
          resources :partnerships, only: [:new, :create, :edit, :update, :destroy]

        end
      end
  end
  get '/users/:user_id/people/new', to: 'people#new'
  post '/users/:user_id/people', to: 'people#create', as: 'user_people'
  get '/sign_in', to: 'sessions#new'
  post '/sign_in', to: 'sessions#create'
  delete '/sign_out', to: 'sessions#destroy'
  get '/', to: 'sessions#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_one :person
  has_one :family, through: :person

  validates :username, uniqueness: true
  has_secure_password

  def to_s
    self.first_name + " " + self.last_name
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:show, :edit, :update, :destroy]
  skip_before_action :check_authentication, only: [:new, :create]

  def show
    @user = User.find(session[:user_id])
  end

  def new
    @user = User.new
    render :layout => false
  end

  def create
    if Person.find_by(first_name: user_params[:first_name], last_name: user_params[:last_name])
      @person = Person.find_by(first_name: user_params[:first_name], last_name: user_params[:last_name])
      @user = User.new(user_params)
      @user.person = @person
    else
      @user = User.new(user_params)
    end
    if @user.save
      redirect_to sign_in_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to new_user_path
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :username, :password)
  end

  def set_user
    @user = User.find(session[:user_id])
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<h1>Edit User Profile</h1>

<%= form_for @user do |f| %>
  <%= f.label :first_name %><br>
  <%= f.text_field :first_name %><br>
  <%= f.label :last_name %><br>
  <%= f.text_field :last_name %><br>
  <%= f.label :username %><br>
  <%= f.text_field :username %><br>
  <%= f.label :password %><br>
  <%= f.text_field :password %><br>
  <%= f.submit %>
<% end %>

app/views/users/new.html.erb
<h1>Create New User Profile</h1>

<%= form_for @user do |f| %>
  <%= f.label :first_name %><br>
  <%= f.text_field :first_name %><br>
  <%= f.label :last_name %><br>
  <%= f.text_field :last_name %><br>
  <%= f.label :username %><br>
  <%= f.text_field :username %><br>
  <%= f.label :password %><br>
  <%= f.text_field :password %><br>
  <%= f.submit %>
<% end %>

<% if flash[:alert] %>
  <div style="color:red"><%= flash[:alert] %></div>
<% end %>

<div><%= link_to "Go To Sign In Page", sign_in_path %></div>

<% @user.errors.messages.each do |attribute, message| %>
  <% if !message.empty? %>
    <p style="color:red"><%= message %></p>
  <% end %>
<% end %>

app/views/users/show.html.erb
<h1>Your Profile:</h1>

<h2>Name: <%= @user.first_name %> <%= @user.last_name %></h2><br>

<% if !@user.person %>
  <%= form_tag "#{@user.id}/people/new", method: "get" do %>
  <%= submit_tag "Create Yourself In Your Family Tree!" %>
  <% end %><br>
  <% else %>
    <h3>Your Person Profile: <%= link_to @user.person.to_s, person_path(@user.person) %></h3>
    <%= form_for @user.person, method: "delete" do |f| %>
    <%= f.submit "Delete Person Profile"%>
    <% end %> <br>
    <div style="color:red">Warning: Deleting this person from your profile will delete all family data.</div>
<% end %>

<% if !@user.family && @user.person %>
  <%= form_tag new_user_family_path(@user), method: "get" do %>
  <%= submit_tag "Create Your Family" %>
  <% end %><br>
<% elsif @user.family %>
  <h3>Your Family: <%= link_to @user.family.name, user_family_path(@user, @user.family) %></h3>
<% end %>

<%= form_tag edit_user_path(@user), method: "get" do %>
<%= submit_tag "Edit User Information" %>
<% end %><br>

<%= form_tag user_path(@user), method: "delete" do %>
<%= submit_tag "Delete User" %><br>
<% end %><br>