config/routes.rb
Rails.application.routes.draw do


  resources :users, except: :index do
      resources :photos
      resources :families, except: :index do
        resources :photos
        resources :people, shallow: true do
          resources :ethnicities, only: [:new, :create, :edit, :update, :destroy]
          resources :relationships, only: [:new, :create, :edit, :update, :destroy]
          resources :partnerships, only: [:new, :create, :edit, :update, :destroy]

        end
      end
  end
  get '/users/:user_id/people/new', to: 'people#new'
  post '/users/:user_id/people', to: 'people#create', as: 'user_people'
  get '/sign_in', to: 'sessions#new'
  post '/sign_in', to: 'sessions#create'
  delete '/sign_out', to: 'sessions#destroy'
  get '/', to: 'sessions#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/partnership.rb
class Partnership < ApplicationRecord
  belongs_to :person
  belongs_to :partner, class_name: "Person"
end

app/controllers/partnerships_controller.rb
class PartnershipsController < ApplicationController

  before_action :person, only: [:new, :create]
  before_action :partnership, only: [:edit, :update, :destroy]

  def edit
    @person = @partnership.person
  end

  def update
    @person = @partnership.person
    if @partnership.update(partnership_params)
      redirect_to person_path(@person)
    else
      render :edit
    end
  end

  def new
    @partnership = @person.partnerships.build
  end

  def create
    @partnership = @person.partnerships.build(partnership_params)
    if @partnership.save
      redirect_to person_path(@person)
    else
      render :new
    end
  end

  def destroy
    @person = @partnership.person
    @partnership.destroy
    redirect_to person_path(@person)
  end

  private

  def partnership_params
    params.require(:partnership).permit(:status, :partner_id)
  end

  def person
    @person = Person.find(params[:person_id])
  end

  def partnership
    @partnership = Partnership.find(params[:id])
  end

  def check_authentication
    if !user_is_signed_in
      flash[:alert] = "you need to sign in to view that"
      redirect_to sign_in_path
    end
  end

  def user_is_signed_in
    @user = User.find(session[:user_id])
    if params[:person_id]
      @person = Person.find(params[:person_id])
    elsif params[:id]
      @partnership = Partnership.find(params[:id])
      @person = @partnership.person
    end
    if params[:user_id]
      session[:user_id] == params[:user_id].to_i
    elsif params[:person_id] || params[:id]
      @user.family == @person.family
    else
      @user = User.find(session[:user_id])
    end
  end

end

app/views/partnerships/edit.html.erb
<h1>Add A Partnership for <%= @person.to_s %></h1>

<%= form_for @partnership, url: partnership_path(@partnership) do |f| %>

  <%= f.label :partner_id %><br>
  <%= f.collection_select :partner_id, @person.family.people, :id, :to_s %><br>
  <br>
  <%= f.label :status, "Status (e.g. divorced, married)" %>
  <%= f.text_field :status %><br>
  <br>
  <%= f.submit %>
<% end %>

app/views/partnerships/new.html.erb
<h1>Add A Partnership for <%= @person.to_s %></h1>

<p>Note: You can only add a partnership with an existing person record.</p>
<p>If you'd like to create a new person, please go back to the <%= link_to "family page", user_family_people_path(@user, @user.family)%>.</p>

<%= form_for @partnership, url: person_partnerships_path(@person) do |f| %>

  <%= f.label :partner_id %><br>
  <%= f.collection_select :partner_id, @person.family.people, :id, :to_s %><br>
  <br>
  <%= f.label :status, "Status (e.g. divorced, married)" %>
  <%= f.text_field :status %><br>
  <br>
  <%= f.submit %>
<% end %>

<% @partnership.errors.messages.each do |attribute, message| %>
  <% if !message.empty? %>
    <p style="color:red"><%= message %></p>
  <% end %>
<% end %>