config/routes.rb
Rails.application.routes.draw do


  resources :users, except: :index do
      resources :photos
      resources :families, except: :index do
        resources :photos
        resources :people, shallow: true do
          resources :ethnicities, only: [:new, :create, :edit, :update, :destroy]
          resources :relationships, only: [:new, :create, :edit, :update, :destroy]
          resources :partnerships, only: [:new, :create, :edit, :update, :destroy]

        end
      end
  end
  get '/users/:user_id/people/new', to: 'people#new'
  post '/users/:user_id/people', to: 'people#create', as: 'user_people'
  get '/sign_in', to: 'sessions#new'
  post '/sign_in', to: 'sessions#create'
  delete '/sign_out', to: 'sessions#destroy'
  get '/', to: 'sessions#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :family, optional: true
  belongs_to :person, optional: true

  validates :name, presence: true
  validates :img_url, presence: true

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :photo, only: [:show, :edit, :update, :destroy]

  def index
    @family = Family.find(params[:family_id])
    @photos = @family.photos
  end

  def show
    @family = @photo.family
  end

  def new
    @photo = Photo.new(photo_type: "profile picture")
  end

  def create
    @photo = Photo.new(photo_params)
    if @photo.valid?
      @photo.save
      if params[:family_id]
        redirect_to user_family_photos_path(@user, @user.family)
      else
        redirect_to person_path(@photo.person)
      end
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @photo.update(photo_params)
      redirect_to photo_path(@photo)
    else
      render :edit
    end
  end

  def destroy
    @family = @photo.family
    @photo.destroy
    redirect_to family_photos_path(@family)
  end

private

  def photo_params
    params.require(:photo).permit(:name, :img_url, :family_id, :person_id, :photo_type)
  end

  def photo
    @photo = Photo.find(params[:id])
  end


end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/edit.html.erb
<h1>Edit Photo</h1>

<%= form_for @photo do |f| %>
  <%= f.label "Name: " %>
  <%= f.text_field :name %><br>
  <br>
  <%= f.label "Photo Type: " %>
  <%= f.text_field :photo_type %><br>
  <br>
  <%= f.label "Family Name: " %><br>
  <%= f.collection_select(:family_id, Family.all, :id, :name) %><br>
  <br>
  <%= f.label "Who's photo is this? " %><br>
  <%= f.collection_select(:person_id, Person.all, :id, :full_name) %><br>
  <br>
  <%= f.submit "Edit Photo" %>
<% end %>

<% @photo.errors.messages.each do |attribute, message| %>
  <% if !message.empty? %>
    <p style="color:red"><%= message %></p>
  <% end %>
<% end %>

app/views/photos/index.html.erb
<h1><%= @family.name %> Photos</h1>
 <%= link_to '<button type="button">Add a Photo</button>'.html_safe, new_user_family_photo_path(@user, @family) %><br>
<br>
<%= link_to '<button type="button">Return to Family Page</button>'.html_safe, user_family_path(@user, @family) %>
<br>
<br>
<% @photos.each do |photo| %>
  <%= link_to (image_tag photo.img_url, :size => "725x450"), user_photo_path(@user, photo)%><br>
<% end %>

app/views/photos/new.html.erb
<h1>New Photo</h1>


<%= form_for @photo, url: user_photos_path(@user) do |f| %>

  <%= f.label "Name: " %>
  <%= f.text_field :name %><br>
  <br>
  <%= f.label "Photo Type: " %>
  <%= f.text_field :photo_type %><br>
  <br>
  <%= f.label "Photo URL: " %>
  <%= f.text_field :img_url %><br>
  <br>


  <%= f.label "Family Name: " %><br>
  <%= f.collection_select(:family_id, [@user.family], :id, :name) %><br>
  <br>
  <%= f.label "Whose photo is this?" %><br>
  <%= f.collection_select(:person_id, @user.family.people, :id, :full_name) %><br>
  <br>
  <%= f.submit "Create Photo" %>
<% end %>

<% @photo.errors.messages.each do |attribute, message| %>
  <% if !message.empty? %>
    <p style="color:red"><%= message %></p>
  <% end %>
<% end %>

app/views/photos/show.html.erb
<h1><%= @photo.name %></h1>
<%= image_tag @photo.img_url, :size => "725x450"%><br>
<br>
<%= link_to '<button type="button">Edit Photo</button>'.html_safe, edit_photo_path(@photo) %><br>
<br>
<%= form_for @photo, method: "delete" do |f| %>
<%= f.submit "Delete Photo"%>
<% end %> <br>

<%= link_to '<button type="button">Return to Family Photos</button>'.html_safe, family_photos_path(@family) %>